### ISSUE TITLE
Package browser for packages

### ISSUE THREAD

**Issue by HENRYMARTIN5** [HENRYMARTIN5/PhLang#8]
Adding a package browser similar to npm or pypi would be great.

**Comment by Froggo8311** [comment]
Perhaps I could help with this?

**Comment by HENRYMARTIN5** [comment]
@Froggo8311 Absolutely! If you could help, it would be amazing.

**Comment by HENRYMARTIN5** [comment]
@Froggo8311 I started development here: https://github.com/HENRYMARTIN5/SolutionPackages

**Comment by HENRYMARTIN5** [comment]
I would call the current state of this finished.
